### ISSUE TITLE
Add FAQ for elasticsearch plugin dependent client

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluentd-docs#537] opened 2018-08-10 04:19 UTC
elasticsearch Ruby client sometimes causes API version mismatch.

[elasticsearch-ruby#compatibility](https://github.com/elastic/elasticsearch-ruby#compatibility) says that users should take care of Elasticsearch and its client library version mismatch but document has no warning or FAQ.
Should we add FAQ or note to prevent version mismatch?

**Comment by fujimotos** [comment] 2018-08-28 10:02
I generally agree that it's worth adding a note somewhere

I'm kinda curious that how td-agent users are handling this issue.
SInce td-agent has all the dependencies packaged, users cannot
help but accepting what td-agent provides, right?

**Comment by fujimotos** [comment] 2018-08-28 10:05
I generally agree that it's worth adding a note somewhere

I'm kinda curious that how td-agent users are handling this issue.
SInce td-agent has all the dependencies packaged, users cannot
help but accepting what td-agent provides, right?

What should they do if their elasticsearch does not have the correct
version?

**Comment by cosmo0920** [comment] 2018-08-29 02:01
td-agent and Fluentd users sometimes fall a pitfall of Elasticsearch version compatibility.
https://github.com/uken/fluent-plugin-elasticsearch/issues/458#issuecomment-411967281

> What should they do if their elasticsearch does not have the correct
version?

Users should confirm their installed elasticsearch client gems and Elasticsearch have same major version.

e.g.) fluent-plugin-elasticsearch with elasticsearch 1.0.19 cannot send data into Elasticsearch 6.x.
But, fluent-plugin-elasticsearch with elasticsearch 6.0.3 can send data into Elasticsearch 6.x.

**Comment by fujimotos** [comment] 2018-08-29 06:27
What is the exact step to resolve the issue *for td-agent users*?

Again, because td-agent bundles all its dependency in its package,
I do not believe there is any feasible way for them to solve the issue.

What are they supposed to do if they find their versions do not match?
Downgrading their Elasticsearch?

**Comment by cosmo0920** [comment] 2018-08-29 06:39
> What are they supposed to do if they find their versions do not match?
> Downgrading their Elasticsearch?

They should upgrade/Downgrade elasticsearch client gems to match elasticsearch protocol.
It is dangerous way to solve this issue.
But there is no safe way to solve it.

**Comment by repeatedly** [comment] 2018-08-29 08:48
Yeah, the problem is elasticsearch ruby client doesn't support multiple es version in one version.
This strategy is not developer friendly...

**Comment by cosmo0920** [comment] 2018-08-30 08:44
I'm trying to another approach which introduces debugging purpose configuration parameter.
https://github.com/uken/fluent-plugin-elasticsearch/pull/463

**Comment by fujimotos** [comment] 2018-08-31 02:03
Patch merged. I close this ticket too.

**Closed by fujimotos** 2018-08-31 02:03 UTC
