### ISSUE TITLE
Deprecated parameter "excludeN" appears in "Life of a Fluentd event" page ( "Filter" section).

### ISSUE THREAD

**Issue by muuuuwa** [fluent/fluentd-docs#414] opened 2018-01-11 06:48 UTC
I found a [deprecated parameter "excludeN"](https://docs.fluentd.org/v1.0/articles/filter_grep#excluden) is used in "Life of a Fluent event" page.

The locations are as follows:
https://github.com/fluent/fluentd-docs/blob/master/docs/v1.0/life-of-a-fluentd-event.txt#L94
https://github.com/fluent/fluentd-docs/blob/master/docs/v1.0/life-of-a-fluentd-event.txt#L132
https://github.com/fluent/fluentd-docs/blob/master/docs/v1.0/life-of-a-fluentd-event.txt#L159
https://github.com/fluent/fluentd-docs/blob/master/docs/v1.0/life-of-a-fluentd-event.txt#L165

**Comment by fujimotos** [comment] 2018-01-11 08:01
Thank you for reporting!

I can confirm this issue in HEAD. The `excludeN` option of `filter_grep`
plugin has been deprecated since v0.12, so we really shouldn't use the
option in v1.0 articles.

I fixed this issue in the patch #415 by migrating these examples to the
new `<exclude>` block syntax. I'll merge this PR tomorrow, so this issue
will be resolved soon.

**Comment by fujimotos** [comment] 2018-01-12 01:35
The pull request got merged. So I close this issue, too.

**Closed by fujimotos** 2018-01-12 01:35 UTC

**Comment by muuuuwa** [comment] 2018-01-12 03:17
Thank you for quick fix. I’m new to fluentd, so this kind of article is very useful for me!
