### ISSUE TITLE
Articles: Buffer Plugin Overview

### ISSUE THREAD

**Issue by ajthenewguy** [fluent/fluentd-docs#255] opened 2017-02-06 18:16 UTC
This article has grammatical errors and omits information.
http://docs.fluentd.org/v0.12/articles/buffer-plugin-overview

> In addition, each chunk is keyed by time and flushed when that chunk’s timestamp has passed. This is different from This immediately raises a couple of questions.

> The backup destination that is used when retry count exceeds retry_limit. Currently, primary plugin type or file plugin works.

The link in last sentence is broken:
> If you are curious which core output plugin use Buffered and which are Time Sliced, please see [the list here](http://docs.fluentd.org/%7B:specified_document_version=%3E%E2%80%9Cv0.12%E2%80%9D%7D/articles/output-plugin-overview#overview)

**Comment by fujimotos** [comment] 2018-01-24 01:55
I took a look at the document and confirmed that these sentences are
actually broken as reported by @ajthenewguy.

To address this issue, I've submitted a few pull requests:

 * #423 : Fix formatting of the article "Buffer Plugin Overview
 * #424 : Make the flow of overview description to easier to follow
 * #425 : Improve the overall structure of the "Buffer Structure" section
 * #426 : A major rewrite of the "Buffer Plugin Overview" article

Since these pull requests are all merged today, I'll close this ticket as
resolved. If you find other problems in the latest version of this article,
please feel free to reopen this ticket.

**Closed by fujimotos** 2018-01-24 01:55 UTC
